import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = <Locale>[Locale('ar'), Locale('en')];

  static const localizationsDelegates = <LocalizationsDelegate<dynamic>>[
    AppLocalizationsDelegate(),
    GlobalMaterialLocalizations.delegate,
    GlobalWidgetsLocalizations.delegate,
    GlobalCupertinoLocalizations.delegate,
  ];

  static const Map<String, Map<String, String>> _values = {
    'ar': {
      'appName': 'Clinic MX',
      'login': 'تسجيل الدخول',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'forgotPassword': 'نسيت كلمة المرور؟',
      'signIn': 'دخول',
      'signOut': 'خروج',
      'dashboard': 'لوحة التحكم',
      'dashboardSubtitle': 'ملخص العيادة اليوم',
      'quickActions': 'إجراءات سريعة',
      'patients': 'المرضى',
      'appointments': 'المواعيد',
      'todayVisits': 'زيارات اليوم',
      'dentalChart': 'خريطة الأسنان',
      'payments': 'المدفوعات',
      'settings': 'الإعدادات',
      'addPatient': 'إضافة مريض',
      'editPatient': 'تعديل مريض',
      'patientProfile': 'ملف المريض',
      'searchPatients': 'ابحث بالاسم أو الهاتف',
      'noPatients': 'لا يوجد مرضى حتى الآن',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'firstName': 'الاسم الأول',
      'fatherName': 'اسم الأب',
      'lastName': 'الاسم الأخير/الجد',
      'phone': 'رقم الهاتف',
      'city': 'المدينة',
      'district': 'الحي',
      'detailedAddress': 'العنوان التفصيلي',
      'dob': 'تاريخ الميلاد',
      'gender': 'الجنس',
      'male': 'ذكر',
      'female': 'أنثى',
      'nationalId': 'الرقم الوطني',
      'reasonForVisit': 'سبب الزيارة',
      'medicalNotes': 'ملاحظات طبية',
      'allergies': 'الحساسيات',
      'chronicDiseases': 'الأمراض المزمنة',
      'attachments': 'المرفقات',
      'optional': 'اختياري',
      'requiredField': 'هذا الحقل مطلوب',
      'invalidArabicName': 'الاسم يجب أن يحتوي حروف عربية صحيحة',
      'invalidPhone': 'رقم الهاتف يجب أن يكون بصيغة E.164 مثل +9647XXXXXXXX',
      'upcomingVisits': 'الزيارات القادمة',
      'pendingPayments': 'مدفوعات معلقة',
      'totalTodayPatients': 'إجمالي مرضى اليوم',
      'createAppointment': 'إنشاء موعد',
      'calendar': 'التقويم',
      'status': 'الحالة',
      'markArrived': 'تسجيل الوصول',
      'reschedule': 'إعادة جدولة',
      'callPatient': 'اتصال',
      'whatsapp': 'واتساب',
      'reminderOffset': 'مدة التذكير قبل الموعد (ساعات)',
      'clinicInfo': 'معلومات العيادة',
      'clinicName': 'اسم العيادة',
      'clinicAddress': 'عنوان العيادة',
      'reminderSettings': 'إعدادات التذكير',
      'whatsappProvider': 'مزود واتساب الرسمي',
      'userManagement': 'إدارة المستخدمين',
      'role': 'الدور',
      'lightTheme': 'فاتح',
      'darkTheme': 'داكن',
      'systemTheme': 'النظام',
      'blurIntensity': 'شدة الضبابية',
      'configureTheme': 'تخصيص الثيم',
      'language': 'اللغة',
      'arabic': 'العربية',
      'english': 'الإنجليزية',
      'dentalActions': 'إجراءات الأسنان',
      'selectPatient': 'اختر المريض',
      'selectAction': 'اختر الإجراء',
      'note': 'ملاحظة',
      'applyToSelected': 'تطبيق على الأسنان المحددة',
      'multiSelectHint': 'اضغط مطولاً لتفعيل تحديد متعدد',
      'clearSelection': 'مسح التحديد',
      'patientsCount': 'عدد المرضى',
      'appointmentReason': 'سبب الموعد',
      'durationMinutes': 'المدة بالدقائق',
      'noData': 'لا توجد بيانات',
      'forgotPasswordTitle': 'استعادة كلمة المرور',
      'sendResetLink': 'إرسال رابط الاستعادة',
      'backToLogin': 'العودة لتسجيل الدخول',
      'passwordResetSent': 'تم إرسال رابط الاستعادة إلى البريد الإلكتروني',
      'loginError': 'فشل تسجيل الدخول',
      'create': 'إنشاء',
      'update': 'تحديث',
      'delete': 'حذف',
      'amount': 'المبلغ',
      'paid': 'المدفوع',
      'remaining': 'المتبقي',
      'method': 'طريقة الدفع',
      'date': 'التاريخ',
      'notes': 'ملاحظات',
      'cash': 'نقداً',
      'card': 'بطاقة',
      'transfer': 'تحويل',
      'today': 'اليوم',
      'week': 'أسبوع',
      'month': 'شهر',
      'day': 'يوم',
      'scheduled': 'مجدول',
      'checkedIn': 'تم الوصول',
      'inTreatment': 'قيد العلاج',
      'completed': 'مكتمل',
      'noShow': 'لم يحضر',
      'cancelled': 'ملغي',
      'addPayment': 'إضافة دفعة',
      'phoneAuthDisabled':
          'تسجيل الدخول عبر الهاتف متاح تصميمياً ويمكن تفعيله من الإعدادات',
      'accessDenied': 'ليس لديك صلاحية للوصول لهذه الصفحة',
      'loading': 'جار التحميل...',
      'retry': 'إعادة المحاولة',
      'register': 'إنشاء حساب',
      'noAccount': 'ليس لديك حساب؟',
      'displayName': 'الاسم الكامل',
      'clinicId': 'معرف العيادة (الاسم)',
      'error': 'خطأ',
      'savedSuccessfully': 'تم الحفظ بنجاح',
      'deletedSuccessfully': 'تم الحذف بنجاح',
      'interactiveDentalChart': 'مخطط الأسنان التفاعلي',
      'selectedToothInfo': 'معلومات السن المختار',
      'numberingSystem': 'نظام الترقيم',
      'selectToothToView': 'اختر سناً لعرض المعلومات',
      'doctorNotes': 'ملاحظات الطبيب',
      'addCustomAction': 'إضافة إجراء مخصص',
      'actionName': 'اسم الإجراء',
      'governorate': 'المحافظة',
      'investigations': 'الفحوصات والأشعة',
      'uploadInvestigation': 'رفع فحص / أشعة',
      'opg': 'OPG بانوراما',
      'xray': 'أشعة سينية',
      'investigation': 'فحص',
      'other': 'أخرى',
      'category': 'التصنيف',
      'uploading': 'جار الرفع...',
      'uploadSuccess': 'تم رفع الملف بنجاح',
      'invalidFileType': 'نوع الملف غير مدعوم (JPEG, PNG فقط)',
      'viewImage': 'عرض الصورة',
    },
    'en': {
      'appName': 'Clinic MX',
      'login': 'Login',
      'email': 'Email',
      'password': 'Password',
      'forgotPassword': 'Forgot password?',
      'signIn': 'Sign in',
      'signOut': 'Sign out',
      'dashboard': 'Dashboard',
      'dashboardSubtitle': 'Today clinic summary',
      'quickActions': 'Quick Actions',
      'patients': 'Patients',
      'appointments': 'Appointments',
      'todayVisits': 'Today Visits',
      'dentalChart': 'Dental Chart',
      'payments': 'Payments',
      'settings': 'Settings',
      'addPatient': 'Add Patient',
      'editPatient': 'Edit Patient',
      'patientProfile': 'Patient Profile',
      'searchPatients': 'Search by name or phone',
      'noPatients': 'No patients yet',
      'save': 'Save',
      'cancel': 'Cancel',
      'firstName': 'First Name',
      'fatherName': 'Father Name',
      'lastName': 'Grandfather/Last Name',
      'phone': 'Phone',
      'city': 'City',
      'district': 'District',
      'detailedAddress': 'Detailed Address',
      'dob': 'Date of Birth',
      'gender': 'Gender',
      'male': 'Male',
      'female': 'Female',
      'nationalId': 'National ID',
      'reasonForVisit': 'Reason for Visit',
      'medicalNotes': 'Medical Notes',
      'allergies': 'Allergies',
      'chronicDiseases': 'Chronic Diseases',
      'attachments': 'Attachments',
      'optional': 'Optional',
      'requiredField': 'Required field',
      'invalidArabicName': 'Arabic name is invalid',
      'invalidPhone': 'Phone must be E.164 format like +9647XXXXXXXX',
      'upcomingVisits': 'Upcoming Visits',
      'pendingPayments': 'Pending Payments',
      'totalTodayPatients': 'Today Total Patients',
      'createAppointment': 'Create Appointment',
      'calendar': 'Calendar',
      'status': 'Status',
      'markArrived': 'Mark Arrived',
      'reschedule': 'Reschedule',
      'callPatient': 'Call',
      'whatsapp': 'WhatsApp',
      'reminderOffset': 'Reminder offset (hours)',
      'clinicInfo': 'Clinic Info',
      'clinicName': 'Clinic Name',
      'clinicAddress': 'Clinic Address',
      'reminderSettings': 'Reminder Settings',
      'whatsappProvider': 'Official WhatsApp Provider',
      'userManagement': 'User Management',
      'role': 'Role',
      'lightTheme': 'Light',
      'darkTheme': 'Dark',
      'systemTheme': 'System',
      'blurIntensity': 'Blur intensity',
      'configureTheme': 'Theme customizations',
      'language': 'Language',
      'arabic': 'Arabic',
      'english': 'English',
      'dentalActions': 'Dental Actions',
      'selectPatient': 'Select Patient',
      'selectAction': 'Select Action',
      'note': 'Note',
      'applyToSelected': 'Apply to selected teeth',
      'multiSelectHint': 'Long press to enable multi-select',
      'clearSelection': 'Clear selection',
      'patientsCount': 'Patients Count',
      'appointmentReason': 'Appointment reason',
      'durationMinutes': 'Duration minutes',
      'noData': 'No data',
      'forgotPasswordTitle': 'Password Recovery',
      'sendResetLink': 'Send recovery link',
      'backToLogin': 'Back to login',
      'passwordResetSent': 'Recovery link sent',
      'loginError': 'Login failed',
      'create': 'Create',
      'update': 'Update',
      'delete': 'Delete',
      'amount': 'Amount',
      'paid': 'Paid',
      'remaining': 'Remaining',
      'method': 'Method',
      'date': 'Date',
      'notes': 'Notes',
      'cash': 'Cash',
      'card': 'Card',
      'transfer': 'Transfer',
      'today': 'Today',
      'week': 'Week',
      'month': 'Month',
      'day': 'Day',
      'scheduled': 'Scheduled',
      'checkedIn': 'Checked in',
      'inTreatment': 'In treatment',
      'completed': 'Completed',
      'noShow': 'No-show',
      'cancelled': 'Cancelled',
      'addPayment': 'Add Payment',
      'phoneAuthDisabled':
          'Phone login is design-ready and can be enabled in settings',
      'accessDenied': 'You do not have access to this page',
      'loading': 'Loading...',
      'retry': 'Retry',
      'register': 'Register',
      'noAccount': "Don't have an account?",
      'displayName': 'Full Name',
      'clinicId': 'Clinic ID / Name',
      'error': 'Error',
      'savedSuccessfully': 'Saved successfully',
      'deletedSuccessfully': 'Deleted successfully',
      'interactiveDentalChart': 'Interactive Dental Chart',
      'selectedToothInfo': 'Selected Tooth Info',
      'numberingSystem': 'Numbering System',
      'selectToothToView': 'Select a tooth to view info',
      'doctorNotes': 'Doctor Notes',
      'addCustomAction': 'Add Custom Action',
      'actionName': 'Action Name',
      'governorate': 'Governorate',
      'investigations': 'Investigations & X-rays',
      'uploadInvestigation': 'Upload Investigation',
      'opg': 'OPG Panoramic',
      'xray': 'X-ray',
      'investigation': 'Investigation',
      'other': 'Other',
      'category': 'Category',
      'uploading': 'Uploading...',
      'uploadSuccess': 'File uploaded successfully',
      'invalidFileType': 'Invalid file type (JPEG, PNG only)',
      'viewImage': 'View Image',
    },
  };

  static AppLocalizations of(BuildContext context) =>
      Localizations.of<AppLocalizations>(context, AppLocalizations)!;

  String tr(String key) {
    final languageCode = locale.languageCode;
    final localized = _values[languageCode] ?? _values['en']!;
    return localized[key] ?? _values['en']![key] ?? key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => AppLocalizations.supportedLocales.any(
    (supported) => supported.languageCode == locale.languageCode,
  );

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(AppLocalizations(locale));
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) =>
      false;
}

extension AppLocalizationsX on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
}
